<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® NonCommercial, 7.6 of lundi 3 mars 2008 on mardi 15 octobre 2019 at 6:46:21</time-stamp>


<methods>
<class-id>CormasNS.Kernel.Entity</class-id> <category>rTransfer</category>

<body package="Cormas" selector="idRTransfer">idRTransfer
	"A method to identify entities for transfer with R (DataTransfR class uses the name of the entity class and this id to reference instances)"
	^self id</body>
</methods>

</st-source>
